### ISSUE TITLE
context name ignored

### ISSUE THREAD

**Issue by jnunyez** [tliron/multusctl#2]
When installing multus specifying a context name that does not exist in the kube config ends up in the installation of multus

``
./multusctl install -x wrong_context_name
``

Current result: Multus gets installed:

``
kube-system   kube-multus-ds-ff2wr              1/1     Running             0          18s
``

Expected result: Provide a message error like "Context Name does not exist in the kubernetes configuration"

**Comment by tliron** [comment]
The issue is in the kutil library, [here](https://github.com/tliron/kutil/blob/main/kubernetes/config.go#L73). Specifically we are creating a deferred (lazy) client, so it's not actually instantiated until used, and thus errors are not detected at this point.

It may be possible to enforce the creation of a client by calling `.ClientConfig()` on it and checking for errors. Or, better, perhaps there is a way to create a non-deferred client?

**Comment by jnunyez** [comment]
Took a look: a possibility could be to use .NewNonInteractiveClientConfig(), https://github.com/kubernetes/client-go/blob/6d69eb8ad66c8962b6ce2f610d46fa3ab7d23afb/tools/clientcmd/client_config.go#L100

This will imply the modification of your library Kutil.
