### ISSUE TITLE
How to add a data to metadata of an openstack instance

### ISSUE THREAD

**Issue by shruthidharani-4313** [tliron/multusctl#4]
How can I add public-ipv4 IPs of the cluster nodes through terraform to this openstack metadata? If so, kindly provide in which module of terraform has this support to add metadata. 

It would be really helpful if someone helps me to get a solution on this. Thanks in advance!

**Comment by tliron** [comment]
Hi @shruthidharani-4313, this repository is specifically for the `multusctl` CLI tool for Multus. Also, I think you are asking a question rather than reporting an issue. Consider posting a discussion [here](https://github.com/k8snetworkplumbingwg/multus-cni/discussions) or on the Multus Slack channel.
